services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/yourdatabase

  service_a:
    build:
      context: .
      dockerfile: ./service_a/Dockerfile
    depends_on:
      - db
      - manager
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/yourdatabase
  service_b:
    build:
      context: .
      dockerfile: ./service_b/Dockerfile
    depends_on:
      - db
      - manager
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/yourdatabase
volumes:
  db_data: